<?php

/**
 * 
 */

/**
* Valid permissions for this module
* @return array An array of valid permissions for the onthisdate module
*/
function ir_bibliography_perm() {
  return array('create ir bibliography');
}


function ir_bibliography_menu() {
  $items = array();
  $items['ir_bibliography'] = array(
    'title' => t('IR Bibliography'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ir_bibliography_form'),
    'type' => MENU_NORMAL_ITEM, //MENU_CALLBACK,
    'access arguments' => array('create ir bibliography'),
  );
  return $items;
}


function ir_bibliography_form() {
    global $user;
    
    $pids = array();
    $status = array();
    if($user->uid){ //get pids assiocated with druapl user from drupal database
        drupal_set_message("from user");
        $query = "SELECT pid FROM {ir_bibliography} WHERE uid = $user->uid";
        $rs = db_query($query); 
        if ($rs) {
            while ($data = db_fetch_object($rs)) {
                $pids[] = $data->pid;
            }
	}
    }
    else{//get pids from session
        //unset($_SESSION['ir_bibliography_pids']);
        $_SESSION['ir_bibliography_pids'] = array('12:1:2121', '121:2121:212','1212:1212e:rdsf');
        drupal_set_message("from session");
        $pids = $_SESSION['ir_bibliography_pids'];
    }    
    //drupal_set_message(print_r($pids));
    if (count($pids) > 0) {
        foreach($pids as $key => $value) {
            $options[$key] = "";
            $form[$key]['pid'] = array('#value' => stripslashes($pids[$key]));
            $form[$key]['title'] = array('#value' => l(t("title link to object "),'http://google.ca'));
            $form[$key]['abstract'] = array('#value' => stripslashes("abstract"));
            $status[$key] = "";
            //$form[$key] = $data->pid;
            
        }
    }
    drupal_set_message(print_r($pids));

    $form['#tree'] == TRUE;

    $form['citation_pids'] = array(
        '#type' => 'hidden',
        '#value' => '',
    );

    $form['citation_check'] = array(
        '#type' => 'checkboxes',
        '#options' => $options,
        '#default_value' => $status,
    );

    $form['citation_action'] = array(
        '#type' => 'select',
        '#title' => t('With Checked'),
        '#options' => array(NULL => "Select...", "Remove","Export"),
        '#required' => TRUE,
    ); //$form['citation_alter'] = array

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );

    $form['cancel'] = array(
        '#type' => 'markup',
        '#value' => l(t('Cancel'), 'ir_bibliography'),
    );

    $form['#redirect'] = 'ir_bibliography';

    return $form;
}

function ir_bibliography_form_submit($form_id, $form) {
    global $user;
    $form_values = $form['values'];
    $citation_check = $form_values['citation_check'];
    $citation_action = $form_values['citation_action'];


    $selected_citations = array();
    foreach($citation_check as $key => $value) {
            if ($value) {
                $selected_citations[] = "'$value'";
            }
    }

    if(count($selected_citations) > 0) {
        //if items are selected
        if ($citation_action == 0) {
            if($user->uid){
                $value_string = @implode(' OR pid = ', $selected_citations);
                $query = "DELETE FROM {ir_bibliography} WHERE (pid = $value_string) AND uid = $user->uid;";
                //drupal_set_message($query);
                db_query($query);
            }
            else {
            //code to delete saved citations from session (anonymous user)
            }
            drupal_set_message(t('Citation(s) removed successfully.'));
        }
        elseif($citation_action == 1) {
            if($user->uid){
                //code to export from DB
            }
            else {
                //code to export from session
            }
            //code to export citations
            drupal_set_message(t('Citation(s) exported successfully.'));
        }
        else {
            drupal_set_message(t('No action defined for selected citations.'));
        }
    }//if(count($selected_citations) > 0)
    else {
        //if no items are selected fire a message
        drupal_set_message(t('No citation(s) were selected.'));
    }

    

    
}

function ir_bibliography_theme() {
	return array(
		'ir_bibliography_form' => array('arguments' => array('form' => NULL),),
	);
}

function theme_ir_bibliography_form($form) {
    $rows = array();
	
    foreach (element_children($form) as $key) {
        //drupal_set_message(count($form));
        $row = array();
	if (isset($form[$key]['pid'])) {
            $row[] = array('data' => drupal_render($form[$key]['pid']));
            $row[] = array('data' => drupal_render($form[$key]['title']));
            $row[] = array('data' => drupal_render($form[$key]['abstract']));
            $status = drupal_render($form['citation_check'][$key]);
            $row[] = array('data' => $status, 'class' => 'checkbox');
            //drupal_set_message($status);
           
            $rows[] = $row;
	}
    }
	// Individual table headers.

	$header = array();
	
	$header[] = t('PID');
	$header[] = t('Title');
	$header[] = t('Abstract');
        $header[] = array('data' => drupal_render($form['citation_action']), 'class' => 'checkbox');

	//$output = theme('table', $header, $rows);
        $output = theme_table($header, $rows, $attributes = NULL);
	$output .= drupal_render($form);
	return $output;
}
